### ISSUE TITLE
Fix popup in bookmarks.html page

### ISSUE THREAD

**Issue by rahulmadaan** [rahulmadaan/mark_it#9]
When we close a popup and re-opens it, the header and the bookmarks didn't appear. There might be some issue while creating a div for popup.

This is the error message : 

bookmarks.js:168 Uncaught TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.
    at createCatPopup (bookmarks.js:168)
    at HTMLDivElement.showPopup (bookmarks.js:199)
createCatPopup @ bookmarks.js:168
showPopup @ bookmarks.js:199
bookmarks.html:1 Error handling response: TypeError: Cannot read property 'appendChild' of null
    at chrome-extension://jjlegaollffncjalafkgmbljjnhgodbp/src/bookmarks.js:165:17
    at Array.map (<anonymous>)
    at chrome-extension://jjlegaollffncjalafkgmbljjnhgodbp/src/bookmarks.js:158:15

**Comment by zeaus** [comment]
Hi @rahulmadaan, 
I would like to work on this.

**Comment by rahulmadaan** [comment]
@zeaus sure, go ahead

**Comment by zeaus** [comment]
Hi @rahulmadaan 

Can you please add the "hacktoberfest" topic to your repository so that it can be counted?

![image](https://user-images.githubusercontent.com/31980558/96298724-611eea00-100c-11eb-99bf-3c728de05a87.png)
